window.PORTFOLIO_DATA = {
  skills: [
    {
      name: "React",
      icon: "images/icon/react.png",
      iconType: "image",
      description: "React 기반 UI 컴포넌트를 개발하고 상태 관리를 활용할 수 있습니다.",
    },
    {
      name: "HTML5",
      icon: "images/icon/html5.png",
      iconType: "image",
      description: "기본적인 HTML 태그를 사용할 수 있습니다.",
    },
    {
      name: "CSS3",
      icon: "images/icon/css3.png",
      iconType: "image",
      description: "반응형 레이아웃과 스타일링을 구현할 수 있습니다.",
    },
    {
      name: "JavaScript",
      icon: "fa-brands fa-js",
      iconType: "font",
      description: "DOM 조작과 인터랙션을 구현할 수 있습니다.",
    },
    {
      name: "TypeScript",
      icon: "images/icon/typeScript.png",
      iconType: "image",
      description: "타입 기반으로 안정적인 코드를 작성할 수 있습니다.",
    },
    {
      name: "Illustrator",
      icon: "images/icon/ai.png",
      iconType: "image",
      description: "간단한 그래픽 리소스를 제작할 수 있습니다.",
    },
    {
      name: "GitHub",
      icon: "fa-brands fa-github",
      iconType: "font",
      description: "Git/GitHub를 활용한 버전 관리가 가능합니다.",
    },
    {
      name: "SVN",
      icon: "fa-solid fa-code-branch",
      iconType: "font",
      description: "SVN을 활용한 협업 및 버전 관리가 가능합니다.",
    },
  ],
  works: [
    {
      title: "필그림스센터 홈페이지 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · React · 반응형",
      image: "images/project/project_pilgrims.png",
      alt: "필그림스센터 홈페이지 썸네일",
      openInModal: true,
      embedUrl: "https://www.pilgrimscenter.org",
      detailUrl: "https://app.notion.com/p/373633f7caaa80e1aabae925d1cc7689?source=copy_link",
    },
    {
      title: "솜씨게임 마녀의 성 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 인터랙티브 콘텐츠",
      image: "images/project/project_somseeGame.png",
      alt: "마녀의 성 썸네일",
      openInModal: true,
      embedUrl:
        "https://somsee.co.kr/ebook_viewer/index.html?contentUrl=/live_nas/live_resource/ebook/Contents/ca88a70d-6228-4186-a56f-a6082f09bebc&page=1",
      detailUrl: "https://app.notion.com/p/373633f7caaa806b984dd3855e6e63c4?source=copy_link",
    },
    {
      title: "수학콕콕 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 인터랙티브 콘텐츠",
      image: "images/project/project_mathkok.png",
      alt: "수학콕콕 썸네일",
      openInModal: true,
      embedUrl:
        "https://somsee.co.kr/ebook_viewer/index.html?contentUrl=/live_nas/live_resource/ebook/Contents/030c80c5-5a74-4655-be09-e81721a7f70e&page=1",
      detailUrl: "https://app.notion.com/p/373633f7caaa80aa9c2af1a7f8e78aa8?source=copy_link",
    },
    {
      title: "금성출판사 음미체실 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 교육 콘텐츠",
      image: "images/project/project_magp.png",
      alt: "금성출판사 음미체실 썸네일",
      url: "https://app.notion.com/p/373633f7caaa804fa717e292764e31a0?source=copy_link",
    },
    {
      title: "금성출판사 아이스쿨 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 인터랙티브 콘텐츠",
      image: "images/project/project_ischool.png",
      alt: "금성출판사 아이스쿨 썸네일",
      url: "https://app.notion.com/p/373633f7caaa802f946ce48d7d32fb43?source=copy_link",
    },
    {
      title: "동아출판사 실과 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 교육 콘텐츠",
      image: "images/project/project_practice.png",
      alt: "동아출판사 실과 썸네일",
      url: "https://app.notion.com/p/373633f7caaa809ca9f3eb3b70c5f492?source=copy_link",
    },
    {
      title: "금성 노래익히기 UI",
      category: "Web | 퍼블리싱 · 프론트엔드 · UI/UX · 유지보수",
      image: "images/project/project_music.png",
      alt: "금성 노래익히기 UI 썸네일",
      url: "https://app.notion.com/p/UI-373633f7caaa80c6a854e7499b2706e9?source=copy_link",
    },
  ],
};
