window.PORTFOLIO_DATA = {
  skills: [
    { name: "React", icon: "images/icon/react.png", iconType: "image" },
    { name: "HTML5", icon: "images/icon/html5.png", iconType: "image" },
    { name: "CSS3", icon: "images/icon/css3.png", iconType: "image" },
    { name: "JavaScript", icon: "fa-brands fa-js", iconType: "font" },
    { name: "TypeScript", icon: "images/icon/typeScript.png", iconType: "image" },
    { name: "Illustrator", icon: "images/icon/ai.png", iconType: "image" },
    { name: "GitHub", icon: "fa-brands fa-github", iconType: "font" },
    { name: "SVN", icon: "fa-solid fa-code-branch", iconType: "font" },
  ],
  works: [
    {
      title: "병원 홈페이지 리뉴얼",
      category: "Web | 퍼블리싱 · SEO · PHP · 반응형",
      image: "images/project/project_pilgrims.png",
      url: "#",
      alt: "병원 홈페이지 리뉴얼 썸네일",
    },
    {
      title: "문자팝",
      category: "Web | 디자인 · 퍼블리싱 · SEO · 유지보수",
      image: "images/project/project_magp.png",
      url: "#",
      alt: "문자팝 웹사이트 썸네일",
    },
    {
      title: "아이엠오 기업 홈페이지 리뉴얼",
      category: "Web | 디자인 · 퍼블리싱 · 풀반응형",
      image: "images/project/project_ischool.png",
      url: "#",
      alt: "아이엠오 기업 홈페이지 썸네일",
    },
    {
      title: "문자팝 모바일 웹",
      category: "UI/UX | 디자인 · 퍼블리싱 · Figma",
      image: "images/project/project_practice.png",
      url: "#",
      alt: "문자팝 모바일 웹 썸네일",
    },
    {
      title: "Mathkok",
      category: "Web | 교육 · 수학학습",
      image: "images/project/project_mathkok.png",
      url: "#",
      alt: "Mathkok 프로젝트 썸네일",
    },
    {
      title: "Music",
      category: "Web | 음악 · 스트리밍",
      image: "images/project/project_music.png",
      url: "#",
      alt: "Music 프로젝트 썸네일",
    },
    {
      title: "Somsee Game",
      category: "Web | 게임 · 인터랙티브",
      image: "images/project/project_somseeGame.png",
      url: "#",
      alt: "Somsee Game 프로젝트 썸네일",
    },
  ],
};
