window.PORTFOLIO_DATA = {
  skills: [
    { name: "React", icon: "images/icon/react.png", iconType: "image" },
    { name: "HTML5", icon: "images/icon/html5.png", iconType: "image" },
    { name: "CSS3", icon: "images/icon/css3.png", iconType: "image" },
    { name: "JavaScript", icon: "fa-brands fa-js", iconType: "font" },
    { name: "TypeScript", icon: "images/icon/typeScript.png", iconType: "image" },
    { name: "Illustrator", icon: "images/icon/ai.png", iconType: "image" },
    { name: "GitHub", icon: "fa-brands fa-github", iconType: "font" },
    { name: "SVN", icon: "fa-solid fa-code-branch", iconType: "font" },
  ],
  works: [
    {
      title: "필그림스센터 홈페이지 홈페이지 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · React · 반응형",
      image: "images/project/project_pilgrims.png",
      url: "https://app.notion.com/p/373633f7caaa80e1aabae925d1cc7689?source=copy_link",
      alt: "필그림스센터 홈페이지 썸네일",
    },
    {
      title: "솜씨게임 마녀의 성 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 인터랙티브 콘텐츠",
      image: "images/project/project_somseeGame.png",
      url: "https://app.notion.com/p/373633f7caaa806b984dd3855e6e63c4?source=copy_link",
      alt: "마녀의 성 썸네일",
    },
    {
      title: "수학콕콕 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 인터랙티브 콘텐츠",
      image: "images/project/project_mathkok.png",
      url: "https://app.notion.com/p/373633f7caaa80aa9c2af1a7f8e78aa8?source=copy_link",
      alt: "수학콕콕 썸네일",
    },
    {
      title: "금성출판사 음미체실 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 교육 콘텐츠",
      image: "images/project/project_magp.png",
      url: "https://app.notion.com/p/373633f7caaa804fa717e292764e31a0?source=copy_link",
      alt: "금성출판사 음미체실 썸네일",
    },
    {
      title: "금성출판사 아이스쿨 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 인터랙티브 콘텐츠",
      image: "images/project/project_ischool.png",
      url: "https://app.notion.com/p/373633f7caaa802f946ce48d7d32fb43?source=copy_link",
      alt: "금성출판사 아이스쿨 썸네일",
    },
    {
      title: "동아출판사 실과 콘텐츠 개발",
      category: "Web | 퍼블리싱 · 프론트엔드 · 교육 콘텐츠",
      image: "images/project/project_practice.png",
      url: "https://app.notion.com/p/373633f7caaa809ca9f3eb3b70c5f492?source=copy_link",
      alt: "동아출판사 실과 썸네일",
    },
    {
      title: "금성 노래익히기 UI",
      category: "Web | 퍼블리싱 · 프론트엔드 · UI/UX · 유지보수",
      image: "images/project/project_music.png",
      url: "https://app.notion.com/p/UI-373633f7caaa80c6a854e7499b2706e9?source=copy_link",
      alt: "금성 노래익히기 UI 썸네일",
    },
  ],
};
